RC 1.3.1 Review
nasa/CryptoLib pull request #276
Opened 2024-08-19 17:43 UTC by rjbrown2

Merge Dev into Main for Release 1.3.1

2024-08-19 17:53 UTC, Donnie-Ice approved these changes

2024-08-19 17:53 UTC, jlucas9 approved these changes
Looks good!

2024-08-19 17:58 UTC, rjbrown2 commented
TODO:

Release paperwork.
Wiki Update.

2024-08-28 15:57 UTC, williamposey requested changes
Just a handful of comments, let me know if there are any questions!

2024-08-28 18:02 UTC, rjbrown2 commented on CMakeLists.txt
> +option(SA_CUSTOM_PATH "Custion Security Association Path" OFF)
Good catch on the typo.  Will fix soon.

2024-08-28 19:09 UTC, rjbrown2 commented on src/core/crypto_config.c
>      // Determine which cryptographic module is in use
#284 
Going to move this to an issue for the future, as this will take some discussion, and larger code massaging.

2024-08-28 19:54 UTC, williamposey commented on src/core/crypto_config.c
>      // Determine which cryptographic module is in use
That sounds good to me! I will resolve for this the sake of this review

2024-08-28 19:54 UTC, williamposey approved these changes

2024-09-09 20:02 UTC, williamposey commented on src/CMakeLists.txt
Just caught this; I reccomend changing line 132 from `set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/cpu${TGTSYS_${SYSVAR}}/${INSTALL_SUBDIR}")` to `set(CMAKE_INSTALL_RPATH "./${INSTALL_SUBDIR}")`

2024-09-11 21:29 UTC, merged